sudo: required

language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - NODE_RELEASE=8.x

before_install:
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs
  - travis_retry composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit
  - npm run eslint